name: CI
on:
  push:
  pull_request:

jobs:
  build:
    name: build-linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-none-eabi

      - name: Build dependencies
        run: |
          echo "Number of processors:" `nproc`
          make get-deps -j `nproc`

      - name: Build CCS32Clara firmware
        run: |
          make clean all

      - uses: actions/upload-artifact@v4
        with:
          name: CCS32Clara firmware binary
          path: stm32_ccs.bin

      - uses: actions/upload-artifact@v4
        with:
          name: CCS32Clara firmware hex
          path: stm32_ccs.hex

  
# Unit tests are currently broken so don't build and run them for now
#- name: Build unit tests on host
#        run: |
#          make -C test
#
#      - name: Run unit tests on host
#        run: |
#          test/test_sine

