name: CI
on:
  push:
  pull_request:

jobs:
  build:
    name: build-linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-none-eabi

      - name: Build dependencies
        run: |
          echo "Number of processors:" `nproc`
          make get-deps -j `nproc`

      - name: Build FlyingADC BMS firmware
        run: |
          make clean all

      - uses: actions/upload-artifact@v4
        with:
          name: BMS firmware binary
          path: stm32_bms*.bin

      - uses: actions/upload-artifact@v4
        with:
          name: BMS firmware hex
          path: stm32_bms*.hex

      - name: Build unit tests on host
        run: |
          make Test

      - name: Run stm32-sine unit tests on host
        run: |
          test/test_bms

      - name: Run libopeninv unit tests on host
        run: |
          libopeninv/test/test_libopeninv
